spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /sample
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/developments/database/h2/sample;AUTO_SERVER=TRUE
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8091